apiVersion: apps/v1
kind: Deployment
metadata:
  name: hitcount
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hitcount
      tier: frontend
  template:
    metadata:
      labels:
        app: hitcount
        tier: frontend
    spec:
      containers:
      - name: hitcount
        image: gregvers/hitcount:latest     # phx.ocir.io/ocicpm/hitcount:latest
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ocirsecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hitcount
      tier: backend
  template:
    metadata:
      labels:
        app: hitcount
        tier: backend
    spec:
      #nodeSelector:
      #  kubernetes.io/hostname: scacab08cn37.us5.kop.internal
      volumes:
      - name: "hitcountdb-data"
        nfs:
          server: scacab08cn40.us5.kop.internal
          path: "/scratch_shared/hitcountdb"
        #persistentVolumeClaim:
        #   claimName: mongodb-master-pvc
        #hostPath:
        #  path: /scratch_local/hitcountdb
        #  type: Directory
      containers:
      - name: mongodb
        image: mongo:4
        volumeMounts:
        - mountPath: "/data/db"
          name: "hitcountdb-data"
        command:
        - mongod
        - "--bind_ip_all"
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: hitcount
    tier: backend
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: hitcount
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: hitcount
  labels:
    app: hitcount
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: hitcount
    tier: frontend
