apiVersion: v1
kind: PersistentVolume
metadata:
  name: hitcountdb-pv
  labels:
    app: hitcount
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/scratch_local/hitcountdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hitcountdb-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
