#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mongodb-master-pv
#  labels:
#    volume: mongodb-master
#spec:
#  accessModes:
#  - ReadWriteOnce
#  capacity:
#    storage: 1Gi
#  nfs:
#    server: scacab08cn40.us5.kop.internal
#    path: "/scratch_shared/mongodb-master"
  # alternatively...
  # hostPath:
  #  path: "/scratch_local/mongodb-master"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-master-pvc
  labels:
    volume: mongodb-master
spec:
  storageClassName: "oci"
  selector:
    matchLabels:
      failure-domain.beta.kubernetes.io/zone: "PHX-AD-1"
      #volume: mongodb-master
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
