kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rolebinding-greg
  namespace: greg
subjects:
- kind: User
  name: greg
  apiGroup: ""
roleRef:
  kind: Role
  name: role-greg
  apiGroup: ""
