kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: greg
  name: role-greg
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]  # ["deployments", "replicasets", "pods", "statefullsets", "namespace"]
  verbs: ["*"]      # ["get", "list", "watch", "create", "update", "patch", "delete"]
