apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    name: pod1
spec:
  containers:
  - image: busybox
    name: pod1
    command: 
      - ping
      - "pod2svc"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    name: pod2
spec:
  containers:
  - image: busybox
    name: pod2
    command:
      - ping
      - "pod1svc"
---
apiVersion: v1
kind: Service
metadata:
  name: pod1svc
spec:
  clusterIP: None
  ports:
  - name: foo
    port: 1234
    targetPort: 1234
  selector:
    name: pod1
---
apiVersion: v1
kind: Service
metadata:
  name: pod2svc
spec:
  clusterIP: None
  ports:
  - name: foo
    port: 1234
    targetPort: 1234
  selector:
    name: pod2
