apiVersion: v1
kind: ConfigMap
metadata:
  name: index
data:
  index: |
    <h1>Greg</h1>
    This page is rendered by Nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: index
      mountPath: /usr/share/nginx/html
  volumes:
  - name: index
    configMap:
      name: index
      items:
      - key: index
        path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
  selector:
    app: web
